### ISSUE TITLE
Hi-C data support

### ISSUE THREAD

**Issue by tinyfallen** [hewm2008/RectChr#1]
Hi dear developer,
Thanks for your excellent tools. Would you like to add some basic visualization support for Hi-C data like hicexplorer or [pygenometracks](https://pygenometracks.readthedocs.io/en/latest/content/examples.html#examples-with-hi-c-data) does in later versions? They are so professional and intricate for a person who only wants a simple plot like me...
Many thanks!
![hic_track](https://user-images.githubusercontent.com/37066354/212224441-20d271d7-f8aa-4698-82c4-5886a253643a.png)

**Comment by hewm2008** [comment]
Sorry, there is no function to draw the picture above （Hi-C data）. I think  that you can use other software to draw it first and then use AI to put it together.     I've been busy recently, so I don't have time to update

**Comment by tinyfallen** [comment]
> Sorry, there is no function to draw the picture above （Hi-C data）. I think that you can use other software to draw it first and then use AI to put it together. I've been busy recently, so I don't have time to update

Thanks for you timely reply and suggestions.
Wish everything goes well with your work!
